import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Heart, ShieldCheck, ShoppingBag, Truck } from 'lucide-react'
import { catalogProducts, formatPrice } from '@/lib/catalog'

export function generateStaticParams() { return catalogProducts.map((product) => ({ slug: product.slug })) }

export default async function ProductDetailsPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const product = catalogProducts.find((item) => item.slug === slug) ?? catalogProducts[0]
  return <main dir="rtl" className="min-h-screen bg-[#FFFDFB] text-[#2f2728]"><header className="border-b border-[#eadfd9] bg-white/90 px-4 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="text-xl font-bold text-[#773441]">سكون</Link><Link href="/products" className="text-sm font-bold text-[#773441]"><ArrowRight className="ml-1 inline" size={15} /> كل المنتجات</Link></div></header><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div className="relative aspect-square overflow-hidden rounded-[2rem] bg-[#f0ebe8]"><Image src={product.image} alt={product.name} fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /><span className="absolute right-5 top-5 rounded-full bg-white/85 px-3 py-1.5 text-xs font-bold text-[#773441]">{product.badge}</span></div><div className="flex flex-col justify-center"><p className="text-sm text-[#a48682]">{product.category}</p><h1 className="mt-3 text-3xl font-bold text-[#3c2b2d] sm:text-5xl">{product.name}</h1><div className="mt-5 flex items-center gap-3"><span className="text-[#9b7d77]">★ {product.rating}</span><span className="text-sm text-[#a48682]">تقييمات موثوقة</span></div><p className="mt-6 text-lg leading-8 text-[#806e6b]">{product.description}</p><div className="mt-6 flex items-baseline gap-3"><span className="text-3xl font-bold text-[#773441]">{formatPrice(product.price)} <small className="text-sm font-normal">ريال</small></span><span className="text-sm text-[#b7a7a3] line-through">{formatPrice(product.oldPrice)} ريال</span></div><div className="mt-7 flex gap-3"><button className="flex flex-1 items-center justify-center gap-2 rounded-full bg-[#773441] px-5 py-4 font-bold text-white transition hover:bg-[#612a36]"><ShoppingBag size={18} /> أضف للسلة</button><button aria-label="إضافة للمفضلة" className="rounded-full border border-[#eadfd9] px-5 text-[#773441] transition hover:bg-[#f8f1ed]"><Heart size={19} /></button></div><div className="mt-8 grid gap-3 border-t border-[#eadfd9] pt-6 sm:grid-cols-3"><div className="flex items-center gap-2 text-xs text-[#806e6b]"><Truck size={17} className="text-[#773441]" /> توصيل موثوق</div><div className="flex items-center gap-2 text-xs text-[#806e6b]"><ShieldCheck size={17} className="text-[#773441]" /> استبدال سهل</div><div className="text-xs text-[#806e6b]">الحالة: <strong className="text-[#773441]">{product.stock}</strong></div></div></div></div><section className="mt-16 max-w-2xl"><h2 className="text-2xl font-bold text-[#3c2b2d]">المواصفات</h2><ul className="mt-5 grid gap-3 sm:grid-cols-3">{product.specs.map((spec) => <li key={spec} className="rounded-2xl bg-[#f8f1ed] p-4 text-sm text-[#806e6b]">{spec}</li>)}</ul></section></div></main>
}
